config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
          
  def new
    @task = Task.new
  end
          
  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end
          
  def edit
    @task = Task.find(params[:id])
  end
          
  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
          
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
    
  def show
    @task = Task.find(params[:id])
  end
            
  def task_params
    params.require(:task).permit(:title, :start_date, :end_date, :all_day, :body)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <header>
        <h1>Ruby on Rails スケジュール管理アプリ</h1>
      </header>
      <%= yield %>
      <div class="push"></div>
      <footer>
        <h1>現在の日時：<%= Date.current.strftime("%Y年%m月%d日") %>　スケジュール合計：<%= Task.count %></h1>
      </footer>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>スケジュール編集</h1>
<%= form_for(@task) do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, 'タイトル' %></th>
      <td><%= f.text_field :title, class: "w_100" %></td>
    </th>
    <tr>
      <th><%= f.label :start_date, '開始日' %></th>
      <td><%= f.date_field :start_date, class: "w_100" %></td>
    </tr>
    <tr>
      <th><%= f.label :end_date, '終了日' %></th>
      <td><%= f.date_field :end_date, class: "w_100" %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, '終日' %></th>
      <td><%= f.check_box :all_day, {}, "○", "" %><br>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
      <th><%= f.label :body, 'スケジュールメモ' %></th>
      <td><%= f.text_area :body, class: "memo" %></td>
    </tr>
  </table>
  <p></p>
  <div><%= f.submit 'スケジュールの編集を完了する', class: "m_left" %></div>
<% end %>
<%= link_to 'スケジュール一覧に戻る', tasks_path, class: "m_left" %>

app/views/tasks/index.html.erb
<h1>スケジュール一覧</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>  
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.start_date.strftime("%Y年%m月%d日") %></td>
        <td><%= task.end_date.strftime("%Y年%m月%d日") %></td>
        <td><%= task.all_day %></td>
        <td><%= task.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
        <td><%= link_to '確認', task_path(task), class: "td_none" %></td>
        <td><%= link_to '編集', edit_task_path(task), class: "td_none" %></td>
        <td><%= link_to '削除', task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "td_none" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'スケジュール新規登録', new_task_path, class: "index_td_none" %>

app/views/tasks/new.html.erb
<h1>スケジュール新規作成</h1>
<%= form_for(@task) do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, 'タイトル' %></th>
      <td><%= f.text_field :title, class: "w_100" %>
        <% if @task.errors.include?(:title) %>
          <div style="color: red;"><%= 'タイトルを入力してください' %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :start_date, '開始日' %></th>
      <td><%= f.date_field :start_date, class: "w_100" %>
        <% if @task.errors.include?(:start_date) %>
          <div style="color: red;"><%= '開始日を選択してください' %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :end_date, '終了日' %></th>
      <td><%= f.date_field :end_date, class: "w_100" %>
        <% if @task.errors.include?(:end_date) %>
          <div style="color: red;"><%= '終了日を選択してください' %></div>
        <% end %>
      </td>
    </tr>
    <tr>
      <th><%= f.label :all_day, '終日' %></th>
      <td><%= f.check_box :all_day, {}, "○", "" %><br>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
      <th><%= f.label :body, 'スケジュールメモ' %></th>
      <td><%= f.text_area :body, class: "memo" %></td>
    </tr>
  </table>
  <p></p>
  <div><%= f.submit 'スケジュールを新規登録する', class: "m_left" %></div>
<% end %>
<%= link_to 'スケジュール一覧に戻る', tasks_path, class: "m_left" %>

app/views/tasks/show.html.erb
<h1>スケジュール詳細</h1>
<%= form_for(@task) do |f| %>
  <table>
    <tr>
      <th><%= 'タイトル' %></th>
      <td><%= @task.title %></td>
    </tr>
    <tr>
      <th><%= '開始日' %></th>
      <td><%= @task.start_date.strftime("%Y年%m月%d日") %></td>
    </tr>
    <tr>
      <th><%= '投稿日時' %></th>
      <td><%= @task.created_at.strftime("%Y年%m月%d日") %></td>
    </tr>
    <tr>
      <th><%= '終日' %></th>
      <td><%= @task.all_day %></td>
    </tr>
    <tr>
      <th><%= 'スケジュールメモ' %></th>
      <td class="show_memo"><%= @task.body %></td>
    </tr>
  </table>
<% end %>
<ul>
  <li><%= link_to 'スケジュール一覧に戻る', tasks_path, class: "show_style" %></li>
  <li><%= link_to 'スケジュールを編集する', edit_task_path, class: "show_style" %></li>
  <li><%= link_to 'スケジュールを削除', task_path, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "show_style" %></li>
</ul>